export const MESSAGE_REGISTRY: Record<string, { category: string; name: string; variables: string[] }> = {
  greeting_menu: { category: 'saudacao', name: 'Saudacao inicial / boas-vindas', variables: ['store_name'] },
  menu_principal: { category: 'menu', name: 'Menu principal', variables: ['store_name'] },
  menu_unknown: { category: 'menu', name: 'Opcao desconhecida do menu', variables: [] },
  product_found: { category: 'produto', name: 'Produto encontrado', variables: ['product_name', 'price', 'stock'] },
  product_not_found: { category: 'produto', name: 'Produto nao encontrado', variables: ['term'] },
  product_unavailable: { category: 'produto', name: 'Produto sem estoque / indisponivel', variables: ['product_name'] },
  product_recommend: { category: 'produto', name: 'Produtos semelhantes (recomendacao)', variables: ['term'] },
  product_list: { category: 'produto', name: 'Lista de opcoes de produtos', variables: [] },
  categories_list: { category: 'produto', name: 'Lista de categorias', variables: [] },
  product_launch: { category: 'produto', name: 'Badge de lancamento', variables: [] },
  search_ask_term: { category: 'produto', name: 'Pedir termo de busca', variables: [] },
  cart_product_added: { category: 'carrinho', name: 'Produto adicionado ao carrinho', variables: ['quantity', 'product_name'] },
  cart_view: { category: 'carrinho', name: 'Visualizacao do carrinho', variables: ['lines', 'total'] },
  cart_remove_menu: { category: 'carrinho', name: 'Pergunta qual item remover', variables: ['numbered'] },
  cart_not_in_cart: { category: 'carrinho', name: 'Produto nao esta no carrinho', variables: ['term'] },
  cart_ambiguous: { category: 'carrinho', name: 'Mais de um item com esse nome', variables: ['numbered'] },
  cart_stock_changed: { category: 'carrinho', name: 'Estoque esgotou durante o pedido', variables: ['items'] },
  checkout_name_short: { category: 'pedido', name: 'Nome muito curto', variables: [] },
  delivery_ask_new_address: { category: 'entrega', name: 'Pedir novo endereco', variables: [] },
  cart_product_capped: { category: 'carrinho', name: 'Produto adicionado com limite de estoque', variables: ['quantity', 'product_name'] },
  cart_product_no_stock: { category: 'carrinho', name: 'Produto sem estoque ao adicionar', variables: ['product_name'] },
  cart_product_removed: { category: 'carrinho', name: 'Produto removido do carrinho', variables: ['product_name'] },
  cart_empty: { category: 'carrinho', name: 'Carrinho vazio', variables: [] },
  cart_clear_confirm: { category: 'carrinho', name: 'Confirmacao para limpar carrinho', variables: [] },
  cart_cleared: { category: 'carrinho', name: 'Carrinho limpo', variables: [] },
  checkout_ask_name: { category: 'pedido', name: 'Iniciar pedido - pedir nome', variables: [] },
  checkout_ask_delivery: { category: 'pedido', name: 'Pedir forma de entrega', variables: [] },
  checkout_ask_address: { category: 'pedido', name: 'Pedir endereco/localizacao', variables: [] },
  checkout_ask_payment: { category: 'pedido', name: 'Pedir forma de pagamento', variables: ['methods'] },
  checkout_ask_cpf: { category: 'pedido', name: 'Pedir CPF (opcional)', variables: [] },
  checkout_summary: { category: 'pedido', name: 'Resumo antes de finalizar', variables: ['lines', 'total', 'delivery', 'payment'] },
  order_confirmed: { category: 'pedido', name: 'Pedido finalizado', variables: ['order_id'] },
  order_canceled: { category: 'pedido', name: 'Pedido cancelado', variables: [] },
  order_ask_min: { category: 'pedido', name: 'Aviso de pedido minimo', variables: ['min_order'] },
  delivery_calculated: { category: 'entrega', name: 'Taxa de entrega calculada', variables: ['address', 'zone', 'fee', 'subtotal', 'delivery', 'total'] },
  delivery_to_combine: { category: 'entrega', name: 'Taxa a combinar', variables: ['address'] },
  delivery_free: { category: 'entrega', name: 'Frete gratis', variables: [] },
  delivery_out_area: { category: 'entrega', name: 'Area nao atendida', variables: [] },
  delivery_ask_location: { category: 'entrega', name: 'Pedir localizacao', variables: [] },
  handoff: { category: 'humano', name: 'Transferencia para atendente', variables: [] },
  handoff_silent: { category: 'humano', name: 'Bot em atendimento humano (silencioso)', variables: [] },
  handoff_released: { category: 'humano', name: 'Retorno ao bot', variables: [] },
  error_generic: { category: 'erro', name: 'Erro generico do sistema', variables: [] },
  error_invalid_qty: { category: 'erro', name: 'Quantidade invalida', variables: ['max'] },
  error_invalid_option: { category: 'erro', name: 'Opcao invalida', variables: [] },
  error_product_invalid: { category: 'erro', name: 'Produto invalido', variables: [] },
  unknown_generic: { category: 'erro', name: 'Mensagem desconhecida', variables: [] },
  timeout_expired: { category: 'timeout', name: 'Conversa expirada', variables: [] },
  timeout_return: { category: 'timeout', name: 'Retorno apos timeout', variables: [] },
};

export const MESSAGE_DEFAULTS: Record<string, string> = {
  greeting_menu: '👋 Olá! Seja bem-vindo à {store_name}!\n\nComo posso ajudar?\n\n1️⃣ Ver produtos\n2️⃣ Consultar preço e estoque\n3️⃣ Fazer um pedido\n4️⃣ Consultar meu pedido\n5️⃣ Falar com atendente\n\nDigite o número da opção desejada.',
  menu_principal: '👋 Olá! Seja bem-vindo à {store_name}!\n\nComo posso ajudar?\n\n1️⃣ Ver produtos\n2️⃣ Consultar preço e estoque\n3️⃣ Fazer um pedido\n4️⃣ Consultar meu pedido\n5️⃣ Falar com atendente\n\nDigite o número da opção desejada.',
  menu_unknown: '🤔 Não consegui entender essa opção.\n\nDigite menu para voltar ao início.',
  product_found: '🔎 Encontrei:\n\n🔥 {product_name}\n\n💰 {price}\n{stock}\n\nDeseja:\n1️⃣ Comprar\n2️⃣ Ver outro produto\n0️⃣ Voltar',
  product_not_found: '😕 Não encontrei produtos com "{term}".\n\nTente outro nome ou digite lista.',
  product_unavailable: '❌ No momento {product_name} está esgotado.',
  product_recommend: '🔎 Não encontrei exatamente "{term}", mas encontrei opções próximas:',
  product_list: 'Sim! 🔥 Encontrei {count} opções disponíveis:',
  categories_list: '📦 Nossos produtos:',
  product_launch: '🔥 LANÇAMENTO',
  search_ask_term: '🔍 Digite o nome do produto que você procura:',
  cart_product_added: '✅ Adicionei {quantity}x {product_name} ao seu carrinho.',
  cart_view: '🛒 Seu carrinho\n\n{lines}\n\nSubtotal: {total}\n\nPode adicionar mais produtos ou digitar "finalizar".',
  cart_remove_menu: '🗑️ Qual item remover?\n\n{numbered}\n\nDigite o número do item.',
  cart_not_in_cart: 'Não encontrei "{term}" no carrinho.',
  cart_ambiguous: 'Há mais de um item assim:\n\n{numbered}\n\nUse o número: ex. "remove 1".',
  cart_stock_changed: '⚠️ Os itens ficaram sem estoque enquanto você montava o pedido:\n{items}\n\nSeu carrinho ficou vazio. Digite menu para recomeçar.',
  checkout_name_short: '📝 Nome muito curto. Digite seu nome completo:',
  delivery_ask_new_address: '📍 Digite o novo endereço ou compartilhe sua localização:',
  cart_product_capped: '⚠️ Temos apenas {quantity} unidade(s) de {product_name} disponível. Posso adicionar {quantity} ao seu carrinho?',
  cart_product_no_stock: '❌ {product_name} está sem estoque no momento.',
  cart_product_removed: '🗑️ Produto removido do carrinho.',
  cart_empty: '🛒 Seu carrinho está vazio.',
  cart_clear_confirm: '⚠️ Limpar todo o carrinho?\n\nDigite SIM para confirmar ou qualquer coisa para cancelar este comando.',
  cart_cleared: '🗑️ Carrinho limpo.\n\nDigite menu para começar um novo pedido.',
  checkout_ask_name: '📝 Qual é o seu nome completo?\n\n(Vamos usar para registrar seu atendimento.)',
  checkout_ask_delivery: '🛵 Como deseja receber?\n\n1️⃣ Retirar na loja\n2️⃣ Receber por entrega\n\nDigite 1 ou 2.',
  checkout_ask_address: '📍 Me envie seu endereço para calcular a entrega.\n\n(Dica: você pode compartilhar sua LOCALIZAÇÃO pelo WhatsApp.)',
  checkout_ask_payment: '💳 Formas de pagamento disponíveis:\n\n{methods}\n\nDigite o número da forma desejada.',
  checkout_ask_cpf: 'Podemos cadastrar seu CPF para nota?\n\nDigite o CPF ou "pular".',
  checkout_summary: '📋 Confirme seu pedido:\n\n{lines}\n\n💰 Total: R$ {total}\n🛵 {delivery}\n💳 {payment}\n\n1️⃣ Confirmar pedido\n0️⃣ Cancelar',
  order_confirmed: '✅ Pedido #{order_id} recebido!\n\nStatus: AGUARDANDO ATENDIMENTO\nEm breve entraremos em contato.',
  order_canceled: '❌ Pedido cancelado.\n\nDigite menu para começar novamente.',
  order_ask_min: '⚠️ Pedido mínimo de R$ {min_order} não atingido.',
  delivery_calculated: '📍 Endereço: {address}\n{zone}\n🛵 Taxa de entrega: {fee}\n\nSubtotal: {subtotal}\nEntrega: {delivery}\nTotal: {total}',
  delivery_to_combine: '📍 Endereço anotado: {address}\n\n🛵 Não consegui calcular a entrega automaticamente.\nPara a taxa exata, compartilhe sua LOCALIZAÇÃO ou continue e confirmamos com você.',
  delivery_free: 'GRÁTIS 🎉',
  delivery_out_area: 'Não entregamos nessa área no momento.',
  delivery_ask_location: '📍 Para calcular a taxa de entrega, envie sua localização pelo WhatsApp.',
  handoff: '👤 Vou encaminhar você para um atendente.\n\nAguarde um momento.',
  handoff_silent: '⏸️ Atendente em conversa.',
  handoff_released: '🤖 De volta ao atendimento automático.',
  error_generic: '😕 Tive um problema momentâneo.\n\nDigite menu para tentar novamente.',
  error_invalid_qty: '⚠️ Quantidade inválida. Informe um número de 1 a {max}.',
  error_invalid_option: '🤔 Não consegui entender essa opção.',
  error_product_invalid: '⚠️ Produto inválido.',
  unknown_generic: '🤔 Não consegui entender exatamente o que você precisa.\n\nPosso ajudar com:\n1️⃣ Ver produtos\n2️⃣ Consultar preço e estoque\n3️⃣ Fazer um pedido\n4️⃣ Consultar meu pedido\n5️⃣ Falar com atendente\n\nOu escreva diretamente o que você procura.',
  timeout_expired: '⏰ A conversa expirou. Estamos de volta! Digite menu para continuar.',
  timeout_return: '⏰ A conversa expirou. Digite menu para começar de novo.',
};
